version: "3.9"  # optional since v1.27.0

volumes:
  i18ngo: { }
  i18ndb: { }
  i18ncache: { }
  i18nqueue: { }

services:
  ianime:
    image: golang
    working_dir: /dir
    volumes:
      - "./anime:/dir"
      - "i18ngo:/go"
    depends_on:
      - iword
    command: [ "go", "run", "." ]
  iword:
    image: golang
    working_dir: /dir
    volumes:
      - "./word:/dir"
      - "i18ngo:/go"
    ports:
      - "8080:8080"
    depends_on:
      - idb
      - icache
      - iadmin
      - iqueue
    command: [ "go", "run", "." ]

  iadmin:
    image: golang
    working_dir: /dir
    volumes:
      - "./admin:/dir"
      - "i18ngo:/go"
    ports:
      - "50051"
    depends_on:
      - idb
      - icache
    command: [ "go", "run", "." ]


  idb:
    image: postgres
    volumes:
      - i18ndb
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: root

  icache:
    image: redis
    ports:
      - "6379"
    volumes:
      - i18ncache

  iqueue:
    image: rabbitmq
    volumes:
      - i18nqueue
    ports:
      - "5672"
      - "15672:15672"
